Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-2204"
    vb.memory = 2048
    vb.cpus = 2
  end

  # Fuerza sincronización de carpeta compartida
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  # Provision con Ansible LOCAL (dentro de la VM)
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/servidor.yml"
  end
end
